### ISSUE TITLE
[Question]: No Ble Signal

### ISSUE THREAD

**Issue by midori-mushi** [mochipon/pysesameos2#9]
### Describe the question you have - 質問の内容

I ran the sample app.
"No Ble Signal" occurs once every two times.
Is my environment not good?
"raspberrypi zero" is located 1 meter away from sesame3.

### Additional context - その他

CHSesame2Status.ReceivedBle
==========
Device status is updated!
UUID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
Device status: CHSesame2Status.BleConnecting
==========
==========
Device status is updated!
UUID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
Device status: CHSesame2Status.WaitingGatt
==========
Task exception was never retrieved
future: <Task finished coro=<CHSesame2.onCharacteristicChanged() done, defined at /home/pi/.local/lib/python3.7/site-packages/pysesameos2/chsesame2.py:244> exception=AttributeError("'NoneType' object has no attribute 'decrypt'")>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pysesameos2/chsesame2.py", line 261, in onCharacteristicChanged
    notify_payload = CHSesame2BleNotify(cipher.decrypt(rawdata))
AttributeError: 'NoneType' object has no attribute 'decrypt'
==========
Device status is updated!
UUID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
Device status: CHSesame2Status.BleLogining
==========
==========
Device status is updated!
UUID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
Device status: CHSesame2Status.NoBleSignal
==========

### Pysesameos2 version (`pip show pysesameos2`)

0.0.2

### Python version (`python --version`)

3.7.3

### OS

Raspbian buster 10.10

### BlueZ version (`bluetoothctl -v`) in case of Linux

5.5.0

**Comment by mochipon** [comment]
Although we do not have enough information to investigate the root cause, I suspect that there is something wrong with the authentication.

You are running [`connect.py`](https://github.com/mochipon/pysesameos2/blob/v0.0.2/example/connect.py), right? The default log level must be `DEBUG`.

https://github.com/mochipon/pysesameos2/blob/84b88cde78aa086109cdea4309660947442525e2/example/connect.py#L12

Do you see this line in your console? This shows that the authentication was successful.

```sh-console
DEBUG:pysesameos2.chsesame2:onCharacteristicChanged: Type=Notify, OpCode=Response, CmdItCode=BleItemCode.login, CmdOPCode=BleOpCode.sync, CmdResultCode=BleCmdResultCode.success
```

If not, please double-check these three lines.

https://github.com/mochipon/pysesameos2/blob/84b88cde78aa086109cdea4309660947442525e2/example/connect.py#L83-L85

**Comment by midori-mushi** [comment]
I have to apologize to you.
Sesame3 wasn't working.

The smartphone app wasn't working properly either.
The lock was open but closed in the app.
When I reset it, it started working properly.

**Comment by mochipon** [comment]
I am glad to hear everything works perfectly!
